frame_id: "world"
tag_list: ["tag1","robot2"]
tag1:
  child_frame_id: "pozyx/tag1"
  id: 7762

robot2:
  child_frame_id: "pozyx/robot2"
  id: 7546
  
#tag3:
#  name: "tag2"
#  child_frame_id: "pozyx/tag3"
#  id: 0000

#tag4:
#  name: "tag2"
#  child_frame_id: "pozyx/tag4"
#  id: 0000
  

