frame_id: "world"
tag_list: ["tag1","robot2","Master_tag"]
tag1:
  child_frame_id: "pozyx/tag1"
  id: 7762

robot2:
  child_frame_id: "pozyx/robot2"
  id: 7546
  
Master_tag:
  child_frame_id: "pozyx/Master_tag"
  id: 30208

#tag4:
#  name: "tag2"
#  child_frame_id: "pozyx/tag4"
#  id: 0000
  

